### ISSUE TITLE
Coroutine Promise example: function cannot be a coroutine: 'std::coroutine_traits<jsbind::Promise<jsbind::Any>>' has no member named 'promise_type'

### ISSUE THREAD

**Issue by blueFrank** [emlite/wasmbind#3]
Hello again,

Sorry to bother you, I was just attempting to make the `promise_coroutine_example.cpp` work and I keep running into this error:

```cpp
promise_coroutine_example.cpp:9:14: error: this function cannot be a coroutine: 'std::coroutine_traits<jsbind::Promise<jsbind::Any>>' has no member named 'promise_type'
    9 | Promise<Any> async_fetch_data() {
```
I've tried to build using `Emscripten` (3.1.74 up to latest), and `Clang` (Apple) seems to have a similar issue.

-----------

Could it be that the `Promise` is missing a `promise_type` in its definition? 🤔 

*(I am really not an expert with `coroutine` so I cannot be sure if something is wrong with my configuration)*

Anyway, thanks for any help!
